# Numpy Reference

---

# Table of Contents

## [Load In NumPy ](#Load-in-NumPy)

## [The Basics ](#The-Basics)

## [Accessing & Changing Specific Elements, Rows, Columns, Etc](#Accessing-and-Changing-Specific-Elements,-Rows,-Columns,-Etc)

## [Initializing Different Types of Arrays ](#Initializing-Different-Types-of-Arrays)

## [Mathematics ](#Mathematics)

### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Linear Algebra ](#Linear-Algebra)

### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Statistics ](#Statistics)

## [Reorganizing Arrays ](#Reorganizing-Arrays)

## [Miscellaneous ](#Miscellaneous)

### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Load Data from File ](#Load-Data-from-File)

### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Boolean Masking and Advanced Indexing ](#Boolean-Masking-and-Advanced-Indexing)

---

## Load in NumPy

In [1]:
import numpy as np

---

## The Basics

In [2]:
# Default dtype = int64/float64
a = np.array([1, 2, 3], dtype="int16")
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [4]:
# Get dimensions
print(a.ndim, b.ndim)

1 2


In [5]:
#Get shape (rows, columns)
print(a.shape, b.shape)

(3,) (2, 3)


In [6]:
# Get type
print(a.dtype, b.dtype)

int16 float64


In [7]:
# Get size (bytes per item)
print(a.itemsize, b.itemsize)

2 8


In [8]:
# Get array size (items in array)
print(a.size, b.size)

3 6


In [9]:
# Get total size
print(a.size * a.itemsize, b.size * b.itemsize)
print(a.nbytes, b.nbytes)

6 48
6 48


---

## Accessing and Changing Specific Elements, Rows, Columns, Etc

In [10]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [row, col]
a[1, 5]
a[1, -2]

13

In [12]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
# Replacement through indexing
a[1, 5] = 20
print(a)
a[:, 2] = 5
print(a)
a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
# 3D example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# 3D indexing (work outside in)
b[0, 1, 1]

4

In [18]:
# 3D indexing
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


---

## Initializing Different Types of Arrays

In [19]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# All 1s matrix
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [21]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [22]:
# Any other number (full-like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# Random decimal numbers
print(np.random.rand(4, 2), end="\n\n")
print(np.random.random_sample(a.shape))

[[0.95069476 0.2964266 ]
 [0.70558005 0.17485877]
 [0.29003564 0.40218244]
 [0.99736211 0.187972  ]]

[[0.99411197 0.86075112 0.47153335 0.21076375 0.10575715 0.44330231
  0.77311448]
 [0.85920297 0.72781679 0.35147436 0.41707363 0.74947669 0.61789017
  0.20432566]]


In [24]:
# Random integer values
np.random.randint(1, 7, size=(3, 3))

array([[2, 3, 2],
       [4, 6, 6],
       [6, 2, 5]])

In [25]:
# Identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
# Repeat array
arr = np.array([[1, 2, 3]])
r1 = arr.repeat(3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
# Practice
output = np.ones((5, 5), dtype="int32")
output[1:4, 1:4] = 0
output[2, 2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays!!!

In [28]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a, b)

[1 2 3] [100   2   3]


---

## Mathematics

In [30]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a * 2

array([2, 4, 6, 8])

In [34]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### [More Functions](https://numpy.org/doc/stable/reference/routines.math.html)

### Linear Algebra

In [41]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
# Find the determinate
c = np.identity(3)
np.linalg.det(c)

1.0

#### [More Functions](https://numpy.org/doc/stable/reference/routines.linalg.html)

### Statistics

In [43]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [46]:
np.max(stats)

6

In [47]:
np.sum(stats)

21

#### [More Functions](https://numpy.org/doc/stable/reference/routines.statistics.html)

---

## Reorganizing Arrays

In [50]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [55]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack((v1, v2, v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [58]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2, h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

#### [More Funcitons](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

---

## Miscellaneous

### Load Data from File

In [62]:
filedata = np.genfromtxt("data.txt", delimiter=",", dtype="int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

### Boolean Masking and Advanced Indexing

In [63]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [64]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [65]:
# Indexing with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [69]:
print(np.any(filedata > 50, axis=0))
print(np.all(filedata > 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]


In [72]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [83]:
# Indexing practice
output = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(output[2:4, 0:2])
print(output[[0, 1, 2, 3], [1, 2, 3, 4]])
print(output[[0, 4, 5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
